# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1198, 737)
        Dialog.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:rgba(0,0,0,0);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color:rgb(245,245,247);\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:4px;\n"
"}")
        self.label_53 = QtWidgets.QLabel(Dialog)
        self.label_53.setGeometry(QtCore.QRect(300, 40, 600, 450))
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setAutoFillBackground(False)
        self.label_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_53.setLineWidth(1)
        self.label_53.setText("")
        self.label_53.setScaledContents(True)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(1100, 510, 72, 15))
        self.label_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.button_53 = QtWidgets.QPushButton(Dialog)
        self.button_53.setGeometry(QtCore.QRect(890, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.button_53.setFont(font)
        self.button_53.setStyleSheet("")
        self.button_53.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_53.setIcon(icon)
        self.button_53.setAutoDefault(False)
        self.button_53.setDefault(False)
        self.button_53.setFlat(False)
        self.button_53.setObjectName("button_53")
        self.label_51 = QtWidgets.QLabel(Dialog)
        self.label_51.setGeometry(QtCore.QRect(20, 430, 80, 60))
        self.label_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_51.setText("")
        self.label_51.setScaledContents(True)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_54 = QtWidgets.QLabel(Dialog)
        self.label_54.setGeometry(QtCore.QRect(920, 370, 160, 120))
        self.label_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_54.setText("")
        self.label_54.setScaledContents(True)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_52 = QtWidgets.QLabel(Dialog)
        self.label_52.setGeometry(QtCore.QRect(120, 370, 160, 120))
        self.label_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_52.setText("")
        self.label_52.setScaledContents(True)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_56 = QtWidgets.QLabel(Dialog)
        self.label_56.setGeometry(QtCore.QRect(20, 510, 72, 15))
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Dialog)
        self.label_57.setGeometry(QtCore.QRect(170, 510, 72, 15))
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.button_52 = QtWidgets.QPushButton(Dialog)
        self.button_52.setGeometry(QtCore.QRect(550, 590, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_52.setFont(font)
        self.button_52.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_52.setIcon(icon1)
        self.button_52.setObjectName("button_52")
        self.label_55 = QtWidgets.QLabel(Dialog)
        self.label_55.setGeometry(QtCore.QRect(1100, 430, 80, 60))
        self.label_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_55.setText("")
        self.label_55.setScaledContents(True)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.button_51 = QtWidgets.QPushButton(Dialog)
        self.button_51.setGeometry(QtCore.QRect(290, 560, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.button_51.setFont(font)
        self.button_51.setStyleSheet("")
        self.button_51.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_51.setIcon(icon2)
        self.button_51.setObjectName("button_51")
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setGeometry(QtCore.QRect(560, 500, 81, 31))
        self.label_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_58.setText("")
        self.label_58.setScaledContents(False)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(960, 510, 72, 15))
        self.label_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "View the detectin results"))
        self.button_52.setText(_translate("Dialog", "Choose"))
import resource_rc
